name: Test Conan Action with external cache

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build-${{ matrix.os }}-${{ matrix.package }}-${{ matrix.shared }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-24.04,
            macos-14,
            macos-15,
            windows-2022,
          ]
        shared: ["True", "False"]
        package: ["fmt/11.2.0", "nlohmann_json/3.12.0", "spdlog/1.15.3"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        id: cache
        with:
            path: ${{ github.workspace }}/.conan2
            key: conan-${{ runner.os }}-${{ hashFiles('.conan2/**/*') }}
            restore-keys: |
              conan-${{ runner.os }}-

      - name: Consume Conan Action
        uses: ./
        with:
          home: ${{ github.workspace }}/.conan2

      - name: Configure Conan profile
        shell: bash
        run: conan profile detect -e --name ${{ matrix.os }}

      - name: List cached Conan packages before build
        shell: bash
        run: conan list -c "${{ matrix.package }}#latest:*"

      - name: Build Conan packages
        shell: bash
        run: |
          conan install -pr:a ${{ matrix.os }} -r conancenter --update --requires=${{ matrix.package }} -o "*/*:shared=${{ matrix.shared }}" --build=missing

      - name: List cached Conan packages after build
        shell: bash
        run: conan list -c "${{ matrix.package }}#latest:*"

      - name: Cache Conan packages
        uses: actions/cache/save@v4
        with:
            path: ${{ github.workspace }}/.conan2
            key: conan-${{ runner.os }}-${{ hashFiles('.conan2/**/*') }}
