name: Test Conan Action with external cache

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-packages:
    name: build-${{ matrix.os }}-${{ matrix.package }}-${{ matrix.shared }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-24.04,
            macos-14,
            macos-15,
            windows-2022,
          ]
        shared: ["True", "False"]
        package: ["fmt/11.2.0", "nlohmann_json/3.12.0", "spdlog/1.15.3", "gtest/1.16.0"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        id: cache
        with:
            path: ${{ github.workspace }}/.conan2
            key: ${{ runner.os }}-conan

      - name: Consume Conan Action
        uses: ./
        with:
          home: ${{ github.workspace }}/.conan2

      - name: Configure Conan profile
        shell: bash
        run: conan profile detect -e --name ${{ matrix.os }}

      - name: List cached Conan packages before build
        shell: bash
        run: conan list -c "*/*#latest:*"

      - name: Build Conan packages
        shell: bash
        id: build-package
        run: |
          conan install -pr:a ${{ matrix.os }} -r conancenter --update --requires=${{ matrix.package }} -o "*/*:shared=${{ matrix.shared }}" --build=missing
          echo "package-id=$(conan graph info -pr:a ${{ matrix.os }} --requires=${{ matrix.package }} -o '*/*:shared=${{ matrix.shared }}' --format=json | jq -r '.graph.nodes."1".package_id')" >> $GITHUB_OUTPUT

      - name: List cached Conan packages after build
        shell: bash
        run: conan list -c "*/*#latest:*"

      - name: Upload Conan cache artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ steps.build-package.outputs.package-id }}
          path: ${{ github.workspace }}/.conan2/p
          overwrite: true
          retention-days: 1
          include-hidden-files: true

  cache-packages:
    runs-on: ubuntu-latest
    needs: [build-packages]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/.conan2
          key: ${{ runner.os }}-conan

      - uses: actions/download-artifact@v4
        with:
          pattern: "package-*"
          path: ${{ github.workspace }}/.conan2/p
          merge-multiple: true

      - name: Consume Conan Action
        uses: ./
        with:
          home: ${{ github.workspace }}/.conan2

      - name: Verify merged artifacts
        run: conan list -c "*/*#latest:*"

      - name: Upload final Conan cache
        uses: actions/cache/save@v4
        with:
          key: ${{ runner.os }}-conan
          path: ${{ github.workspace }}/.conan2
